### ISSUE TITLE
*1.19.3 Error

### ISSUE THREAD

**Issue by Jake-Moore** [AdomasDauda/ConvincingOldPVP#2]
Installed the plugin and it's occasionally throwing this error.

```
[06:29:41 ERROR]: [ConvincingOldPVP] Unhandled exception occurred in onPacketSending(PacketEvent) for ConvincingOldPVP
java.lang.IllegalStateException: Unable to invoke method public static org.bukkit.Sound org.bukkit.craftbukkit.v1_19_R2.CraftSound.getBukkit(net.minecraft.sounds.SoundEffect)
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:25) ~[ProtocolLib-610.jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$20.getSpecific(BukkitConverters.java:1131) ~[ProtocolLib-610.jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$20.getSpecific(BukkitConverters.java:1117) ~[ProtocolLib-610.jar:?]
        at com.comphenix.protocol.wrappers.Converters$1.getSpecific(Converters.java:50) ~[ProtocolLib-610.jar:?]
        at com.comphenix.protocol.wrappers.Converters$7.getSpecific(Converters.java:254) ~[ProtocolLib-610.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:274) ~[ProtocolLib-610.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.readSafely(StructureModifier.java:248) ~[ProtocolLib-610.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.getValues(StructureModifier.java:457) ~[ProtocolLib-610.jar:?]
        at io.github.adomasdauda.ConvincingOldPVP$1.onPacketSending(ConvincingOldPVP.java:51) ~[ConvincingOldPVP-1.0.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib-610.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib-610.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib-610.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib-610.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib-610.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib-610.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib-610.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib-610.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib-610.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java) ~[?:?]
        at net.minecraft.network.Connection.a(Connection.java) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.a(ServerGamePacketListenerImpl.java) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.a(ServerGamePacketListenerImpl.java) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.playSound() ~[pufferfishplus-1.19.3.jar:git-PufferfishPlus-40]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.playSound() ~[pufferfishplus-1.19.3.jar:git-PufferfishPlus-40]
        at ia.m.eA.f(SourceFile:60) ~[ItemsAdder_3.3.1.jar:?]
        at ia.m.es.b(SourceFile:83) ~[ItemsAdder_3.3.1.jar:?]
        at ia.m.bU.a(SourceFile:235) ~[ItemsAdder_3.3.1.jar:?]
        at ia.m.bU.a(SourceFile:366) ~[ItemsAdder_3.3.1.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run() ~[pufferfishplus-1.19.3.jar:git-PufferfishPlus-40]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat() ~[pufferfishplus-1.19.3.jar:git-PufferfishPlus-40]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java) ~[pufferfishplus-1.19.3.jar:git-PufferfishPlus-40]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java) ~[pufferfishplus-1.19.3.jar:git-PufferfishPlus-40]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java) ~[pufferfishplus-1.19.3.jar:git-PufferfishPlus-40]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java) ~[pufferfishplus-1.19.3.jar:git-PufferfishPlus-40]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java) ~[pufferfishplus-1.19.3.jar:git-PufferfishPlus-40]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.MinecraftKey.b()" because "IIIIlIIlIlIllIl" is null
        at org.bukkit.craftbukkit.v1_19_R2.util.CraftNamespacedKey.fromMinecraft() ~[pufferfishplus-1.19.3.jar:git-PufferfishPlus-40]
        at org.bukkit.craftbukkit.v1_19_R2.CraftSound.getBukkit() ~[pufferfishplus-1.19.3.jar:git-PufferfishPlus-40]
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[ProtocolLib-610.jar:?]
        ... 35 more
[06:29:41 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutNamedSoundEffect@72380151[
    b=Direct{net.minecraft.sounds.SoundEffect@140c382f}
    c=MASTER
    d=11668
    e=568
    f=-524
    g=1.0
    h=1.0
    i=7221299754030618981
  ]
```

**Comment by AdomasDauda** [comment]
Can you specify the minecraft version you are running?

This issue could be caused by incorrect version of ProtolLib. If the version is 1.19.3 then you have to use a dev build of protocollib accessible [here](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/target/ProtocolLib.jar)

**Comment by AdomasDauda** [comment]
What is your version of protocolLib?

**Comment by 0xleft** [comment]
You should use build [606](https://ci.dmulloy2.net/job/ProtocolLib/606/artifact/target/ProtocolLib.jar) of protocollib for 1.19.2. I see you are using 610

**Comment by 0xleft** [comment]
Can you tell me the enviroment this is in? I'm trying to replicate this myself and I'm not able to.

**Comment by Jake-Moore** [comment]
Typo mb, I meant 1.19R2
For 1.19.3

It's possible b610 is too old for 1.19.3

**Comment by 0xleft** [comment]
Could you try using 612 then?

**Comment by 0xleft** [comment]
I will try to replicated your environment later when I have time and see if the error persists
